FROM ubuntu:22.04

WORKDIR /root/
ENV DEBIAN_FRONTEND="noninteractive"

### Install dependencies

RUN apt-get update && \
    apt-get -yy install \
      wget apt-transport-https git unzip \
      build-essential libtool libtool-bin gdb \
      automake autoconf bison flex sudo vim \
      curl software-properties-common \
      python3 python3-pip libssl-dev pkg-config libffi-dev\
      libsqlite3-0 libsqlite3-dev apt-utils locales \
      libleveldb-dev python3-setuptools \
      python3-dev pandoc python3-venv \
      libgmp-dev libbz2-dev libreadline-dev libsecp256k1-dev locales-all

### Prepare a user account

RUN useradd -ms /bin/bash test
RUN usermod -aG sudo test
RUN echo "test ALL=(ALL:ALL) NOPASSWD:ALL" >> /etc/sudoers
USER test
WORKDIR /home/test

### Install smart contract testing tools
RUN mkdir /home/test/tools

# Install ityFuzz
COPY --chown=test:test ./docker-setup/ityfuzz /home/test/tools/ityfuzz
RUN /home/test/tools/ityfuzz/install_ityfuzz.sh

# Add scripts for each tool
COPY --chown=test:test ./docker-setup/tool-scripts/ /home/test/scripts

### Prepare benchmarks

COPY --chown=test:test ./benchmarks /home/test/benchmarks

CMD ["/bin/bash"]
